#application: fortune-teller
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers: #order matters, so leave static stuff above
- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: javascript #directory

- url: /images
  static_dir: pictures
#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico

#static directories should go ABOVE the catch all url (.*)
- url: .* #any random links in website go to main/home script file
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
